### ISSUE TITLE
Response as JSON and unify response writing

### ISSUE THREAD

**Issue by rluders** [GbSouza15/apiToDoGo#1]
For your handlers that are returning JSON, it is important to say that it is a JSON response to the HTTP header:

```go
w.Header().Set("Content-Type", "application/json")
```

I  would probably also create a helper function, and use it to write the responses:

```go
func sendResponse(code int, data []byte) {
    w.Header().Set("Content-Type", "application/json")
    w.WriteHeader(code)
    w.Write(data)
}
```

**Comment by GbSouza15** [comment]
https://github.com/GbSouza15/apiToDoGo/commit/99dc121faca130e35bea9770ebde217858491aa9
